### ISSUE TITLE
Problem with deploying

### ISSUE THREAD

**Issue by hassos246** [youroldmangaming/MeshSense#6]
Hi,

Trying to deploy this as a stack using portainer.

Code used:

```
services:
  meshsense:
    image: y0mg/meshsense
    ports:
      - "5921:5921"
      - "5920:5920"
    environment:
      - PORT="5921"
      - DEV_UI_URL="http://10.0.0.10:5921"
      - ACCESS_KEY="noSecrets"
    tty: true
    stdin_open: true
    privileged: true  # Run the container in privileged mode
```

Results, I can open the page on both ports. But every try to enter the access key fails. On 5921 nothing happens at all. On 5920 I get a message that I typed the wrong key, even if copying from the code.
